// @/types/item.ts
import { IdSchemaType } from "@/schemas/id";

// The type used for ids generated by the client
export type ClientIdType = IdSchemaType;

export enum ItemDisposition {
  New = "NEW",
  Modified = "MODIFIED",
  Synced = "SYNCED",
}
